/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mapa_psii_alexandreoliveira;

/**
 *
 * @author alexandre.oliveira
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCadastrar = new javax.swing.JButton();
        jLabelBoasVindas = new javax.swing.JLabel();
        jLabelNomeHotel = new javax.swing.JLabel();
        jButtonReservar = new javax.swing.JButton();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonCadastrar.setText("Cadastrar Hospede");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastrar);
        jButtonCadastrar.setBounds(90, 260, 160, 50);

        jLabelBoasVindas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelBoasVindas.setForeground(new java.awt.Color(51, 51, 51));
        jLabelBoasVindas.setText("Seja bem vindo, nossa missão e melhor lhe atender!!");
        getContentPane().add(jLabelBoasVindas);
        jLabelBoasVindas.setBounds(310, 350, 460, 70);

        jLabelNomeHotel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelNomeHotel.setForeground(new java.awt.Color(0, 0, 255));
        jLabelNomeHotel.setText("Hotel MAPA PSII");
        getContentPane().add(jLabelNomeHotel);
        jLabelNomeHotel.setBounds(410, 280, 240, 80);

        jButtonReservar.setText("Reservar ");
        jButtonReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReservarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReservar);
        jButtonReservar.setBounds(90, 360, 160, 50);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mapa_psii_alexandreoliveira/tala inicio.png"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(-3, -4, 820, 540);

        setSize(new java.awt.Dimension(833, 542));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
     new TelaCadastro().setVisible(true);
        
        this.dispose();
        
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReservarActionPerformed
        new TelaReserva().setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jButtonReservarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonReservar;
    private javax.swing.JLabel jLabelBoasVindas;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelNomeHotel;
    // End of variables declaration//GEN-END:variables
}
