package mapa_psii_alexandreoliveira;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author alexandre.oliveira
 */
public class TelaReserva extends javax.swing.JFrame {
    List<ReservaHotel> ListarH = new ArrayList<ReservaHotel>();
    //suites
    public int suite10 = 0;
    public int suite20 = 0;
    public int suite30 = 0;
    public int suite40 = 0;
    public int suite50 = 0;
    public int suite60 = 0;
    public int suite70 = 0;
    public int suite80 = 0;
    public int disponibilidade =0;
    public double valorPagar = 0.00;
    public double valorDiarias = 0.00;
    public double desconto = 0.00;
    
    public int qtDiarias = 0;
    public int qtPessoas = 0;
    public int qtCriancas = 0;
    public double valorSuite = 0.00;
    public int compDisponib =0;
    public int numeroReserva = 0;
    
    /**
     * Creates new form TelaReserva
     */
    public TelaReserva() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelValorPagar = new javax.swing.JLabel();
        jTextFieldTipoSuite = new javax.swing.JTextField();
        jTextFieldNomeResponsavel = new javax.swing.JTextField();
        jTextFieldQtPessoas = new javax.swing.JTextField();
        jLabelCapasidade = new javax.swing.JLabel();
        jTextFieldQtCrianca = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldQtDiarias = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabelDesconto = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Quantidade de Diarias:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 210, 130, 16);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Quantidade de Pessoas:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 240, 150, 16);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Hospede Responsavel:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(180, 300, 140, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Reservar Suite");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(250, 120, 150, 25);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Valor a pagar:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(570, 150, 100, 16);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Capasidade da suite:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(490, 190, 120, 20);

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 410, 72, 22);

        jButton2.setText("Reservar Suite");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(580, 400, 200, 60);

        jButton3.setText("Calcular calor /Disponibilidade");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(580, 300, 200, 60);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(720, 100, 90, 30);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(710, 190, 100, 0);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Suite Tipo(Standard ou Luxo:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(210, 180, 170, 16);

        jLabelValorPagar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelValorPagar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelValorPagar.setText("R$");
        getContentPane().add(jLabelValorPagar);
        jLabelValorPagar.setBounds(660, 150, 90, 16);

        jTextFieldTipoSuite.setText("Standard");
        jTextFieldTipoSuite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTipoSuiteActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldTipoSuite);
        jTextFieldTipoSuite.setBounds(380, 180, 100, 22);

        jTextFieldNomeResponsavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeResponsavelActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNomeResponsavel);
        jTextFieldNomeResponsavel.setBounds(310, 300, 200, 22);

        jTextFieldQtPessoas.setText("0");
        getContentPane().add(jTextFieldQtPessoas);
        jTextFieldQtPessoas.setBounds(380, 240, 100, 22);

        jLabelCapasidade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCapasidade.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCapasidade.setText("--");
        getContentPane().add(jLabelCapasidade);
        jLabelCapasidade.setBounds(610, 190, 210, 20);

        jTextFieldQtCrianca.setText("0");
        getContentPane().add(jTextFieldQtCrianca);
        jTextFieldQtCrianca.setBounds(380, 270, 100, 22);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Quantidade de crianças ate 2 anos :");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(170, 270, 200, 16);

        jTextFieldQtDiarias.setText("0");
        getContentPane().add(jTextFieldQtDiarias);
        jTextFieldQtDiarias.setBounds(380, 210, 100, 22);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Desconto:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(570, 170, 80, 20);

        jLabelDesconto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelDesconto.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDesconto.setText("RS");
        getContentPane().add(jLabelDesconto);
        jLabelDesconto.setBounds(660, 170, 80, 16);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mapa_psii_alexandreoliveira/reserva hotel.png"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(-3, -4, 820, 540);

        setSize(new java.awt.Dimension(832, 542));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String TipoSuite = jTextFieldTipoSuite.getText();
        String QtDiarias = jTextFieldQtDiarias.getText();
        String QtPessoas = jTextFieldQtPessoas.getText();
        String QtCrianca = jTextFieldQtCrianca.getText();
        String NomeResponsavel = jTextFieldNomeResponsavel.getText();
        
        //int numeroConvertido = Integer.parseInt(numero);
        int qtDiarias = Integer.parseInt(QtDiarias);
        int qtCriancas = Integer.parseInt(QtCrianca);
        int qtPessoas = Integer.parseInt(QtPessoas); 
       
        if (TipoSuite.equals("Standard")){
            valorDiarias =  130 * qtDiarias;
        }
        
        
       
        if (TipoSuite.equals("Luxo")){
            valorDiarias = 180 * qtDiarias;
        }
        
        
        //calcularValorDiarias();
      
        if(qtDiarias >= 7 ){
        desconto = valorDiarias * 0.1;
        
        }
        
        if(qtDiarias <= 7 ){
         valorPagar = valorDiarias;
        }
                
        valorPagar = valorDiarias - desconto;        
       
        
        
        jLabelValorPagar.setText(""+ valorPagar);
        jLabelDesconto.setText(""+ desconto);
        
        compDisponib = qtPessoas-qtCriancas; 
        
        if( compDisponib >= 4 ){
        jLabelCapasidade.setText("Camas insuficientes" );
        }
        
        if(compDisponib <= 3 ){
        jLabelCapasidade.setText(" Suite com camas disponiveis"  );
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextFieldTipoSuiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTipoSuiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTipoSuiteActionPerformed

    private void jTextFieldNomeResponsavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeResponsavelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeResponsavelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         new TelaInicial().setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String TipoSuite = jTextFieldTipoSuite.getText();
        String QtDiarias = jTextFieldQtDiarias.getText();
        String QtPessoas = jTextFieldQtPessoas.getText();
        //String QtCrianca = jTextFieldQtCrianca.getText();
        String NomeResponsavel = jTextFieldNomeResponsavel.getText();

       ReservaHotel rH = new ReservaHotel();
       
       numeroReserva = numeroReserva + 1;
       int qtDiarias = Integer.parseInt(QtDiarias);
       int qtPessoas = Integer.parseInt(QtPessoas); 
       
       rH.setNomeResponsavel(NomeResponsavel);
       rH.setNumeroReserva(numeroReserva);
       rH.setQuantidadePessoas(qtPessoas);
       rH.setSuiteTipo(TipoSuite);
       
       ListarH.add(rH);
        
        System.out.print(ListarH.get(0).getNomeResponsavel());
        
        this.dispose();
        
        new TelaReservaOK().setVisible(true);
        
        

    }//GEN-LAST:event_jButton2ActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaReserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCapasidade;
    private javax.swing.JLabel jLabelDesconto;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelValorPagar;
    private javax.swing.JTextField jTextFieldNomeResponsavel;
    private javax.swing.JTextField jTextFieldQtCrianca;
    private javax.swing.JTextField jTextFieldQtDiarias;
    private javax.swing.JTextField jTextFieldQtPessoas;
    private javax.swing.JTextField jTextFieldTipoSuite;
    // End of variables declaration//GEN-END:variables
}
